### ISSUE TITLE
IsCurrentModuleNameConstraint / getCurrentModuleName returns wrong module name if one is substring of another

### ISSUE THREAD

**Issue by mvoelker** [laminas/laminas-test#37] opened 2021-07-06 16:04 UTC
### Bug Report

Method `getCurrentModuleName` of new class `IsCurrentModuleNameConstraint` returns wrong module name due to weak `strpos` check if a module name is part of another module name.

|    Q        |   A
|------------ | ------
| Version(s)  | 3.5.1

#### Summary

We do have module names `ElasticSearchApi` and `SearchApi`.
Since version 3.5.0 the method `assertModuleName` of class `AbstractControllerTestCase` does not work correctly anymore.
Reason is the `strpos` check in `foreach` loop in the method `getCurrentModuleName` of the new class `IsCurrentModuleNameConstraint`.
As `SearchApi` is a substring of `ElasticSearchApi` our unit test reports the wrong module name `searchapi` in a unit test for the `ElasticSearchApi` expecting `elasticsearchapi`.

#### Current behavior

Running the unit test for the module `ElasticSearchApi` expecting a module name of `elasticsearchapi`. Test fails with this error message:
`Failed asserting that "elasticsearchapi" is the actual module name, actual module name is "searchapi"`

#### How to reproduce

- Have two modules named e.g. `WorkApi` and `SpecialWorkApi`
- Create a dispatch test for the `SpecialWorkApi`
- Testing: `$this->assertModuleName('specialworkapi');`
- You'll get a similar PHPUnit error like mentioned above

#### Expected behavior

Correct module name returned from `IsCurrentModuleNameConstraint / getCurrentModuleName()`.

**Comment by mvoelker** [comment] 2021-07-06 16:21
Tried how to get it running. Found a solution (for me). A comparion of `starts-with` instead of `contains` helps:
```
--- a/zend/vendor/laminas/laminas-test/src/PHPUnit/Constraint/IsCurrentModuleNameConstraint.php
+++ b/zend/vendor/laminas/laminas-test/src/PHPUnit/Constraint/IsCurrentModuleNameConstraint.php
@@ -40,7 +40,7 @@ final class IsCurrentModuleNameConstraint extends LaminasConstraint
 
         // Find Module from Controller
         foreach ($applicationConfig['modules'] as $appModules) {
-            if (strpos($controllerClass, $appModules) !== false) {
+            if (strpos($controllerClass, $appModules) === 0) {
                 if (strpos($appModules, '\\') !== false) {
                     $match = ltrim(substr($appModules, strrpos($appModules, '\\')), '\\');
                 } else {
```

As mentioned ... in my case.

**Comment by froschdesign** [comment] 2021-07-06 18:26
Duplicate of #34. See also the related pull request: #36 
Please add your comments and solution there. Thanks!

**Closed as completed by froschdesign** 2021-07-06 18:26 UTC
Labels: Bug, Duplicate
